apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  lables:
    type: local
spec: 
  storageClassName: manual
  capacity:
    sorage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
